# Generated by Django 4.2.29 on 2026-03-25 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, max_length=200)),
                ('population', models.IntegerField(default=0)),
                ('centroid_lat', models.FloatField(default=0)),
                ('centroid_lng', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['ward_no'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Garbage Burning', 'Garbage Burning'), ('Construction Dust', 'Construction Dust'), ('Traffic Congestion', 'Traffic Congestion'), ('Industrial Smoke', 'Industrial Smoke'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(default=3)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='wards.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AQIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi', models.IntegerField()),
                ('pm25', models.FloatField(blank=True, help_text='PM2.5 µg/m³', null=True)),
                ('pm10', models.FloatField(blank=True, help_text='PM10 µg/m³', null=True)),
                ('no2', models.FloatField(blank=True, help_text='NO2 µg/m³', null=True)),
                ('so2', models.FloatField(blank=True, help_text='SO2 µg/m³', null=True)),
                ('co', models.FloatField(blank=True, help_text='CO µg/m³', null=True)),
                ('o3', models.FloatField(blank=True, help_text='O3 µg/m³', null=True)),
                ('source', models.CharField(choices=[('aqicn', 'AQICN Station'), ('openmeteo', 'OpenMeteo'), ('interpolated', 'Interpolated'), ('seeded', 'Seeded/Fallback')], default='seeded', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='wards.ward')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ward', '-timestamp'], name='wards_aqire_ward_id_832d66_idx')],
            },
        ),
    ]
